development:
  adapter: mysql2
  database: gf_core_development
  host: localhost
  username: root

test:
  adapter: mysql2
  database: gf_core_test
  host: localhost
  username: root

production:
  adapter: mysql2
  database: gf_core
  host: localhost
  username: root
  password: ex171aY555
