development:
  adapter: mysql2
  database: gf_internal_development
  host: localhost
  username: root

test:
  adapter: mysql2
  database: gf_internal_test
  host: localhost
  username: root

production:
  adapter: mysql2
  database: gf_internal
  host: localhost
  username: root
  password: ex171aY555
